# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-deploy
  labels:
    app: amazon-prime-app
spec:
  selector:
    matchLabels:
      app: amazon-prime-app
  replicas: 2

  template:
    metadata:
      labels:
        app: amazon-prime-app
    spec:
      containers:
      - name: amazon-prime-container
        image: 752948842505.dkr.ecr.ap-south-1.amazonaws.com/amazon-prime:40
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-svc
spec:
  selector:
    app: amazon-prime-app
  type: LoadBalancer

  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80